apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: virtual-kubelet
      docker:
        dockerfile: hack/skaffold/virtual-kubelet/Dockerfile
manifests:
  rawYaml:
    - hack/skaffold/virtual-kubelet/base.yml
    - hack/skaffold/virtual-kubelet/pod.yml
deploy:
  kubectl: {}
profiles:
  - name: local
    build:
      local: {}
